- name: package installation java
  ansible.builtin.package:
    state: present
    name: "{{pkg}}"

- name: package update
  shell: yum update -y

- name: package download tomcat
  ansible.builtin.get_url:
     url: "{{tmcurl}}"
     dest: /opt/

- name: package unzip tomcat
  ansible.builtin.unarchive:
     src: "{{TC_last}}"
     dest: /opt/
     mode: 0775
     remote_src: yes 

- name: download student.war
  ansible.builtin.get_url:
    url: "{{studentwar}}"
    dest: "{{TC-dir}}/webapps/"

- name: download student.jar
  ansible.builtin.get_url: 
    url: "{{studentjar}}"
    dest: "{{TC-dir}}/lib/"

- name: start tomcat service
  shell: "nohup {{TC-dir}}/bin/startup.sh"