- name: installation of packages
  hosts: all
  become: yes
  tasks: 
    - name: Install the latest version of Apache and tree
      ansible.builtin.package:
        name:
          - httpd
          - tree
        state: present

   